project:
  type: website

website:
  title: "CodeBubo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: secondary

format:
  html:
    theme: cosmo
    css: styles.css
    backgroundcolor: floralwhite
    toc: true



