%% Byggs med mmdc -i chart1.mmd -o chart1.svg -t dark -b transparentfg
%%{init: {
    "flowchart": {
        "curve": "linear"
    },
    "theme": "base",
    "themeVariables": {
        "primaryTextColor": "#FFFFFF",
        "lineColor": "#FFFFFF",
        "fontFamily": "Times New Roman, serif",
        "primaryColor": "transparent",
        "primaryBorderColor": "#FFFFFF",
        "edgeLabelBackground": "#000000",
        "labelTextColor": "#FFFFFF"
    }
}}%%
flowchart LR
    start[/Inmatning<br>poäng/]
    cond{Är poäng över<br>E-gräns?}
    ja[/Skriv ut<br>Godkänt/]
    nej(Programmet<br>avslutas)
    start-->cond
    cond-->|Ja|ja
    cond-->|Nej|nej
    ja-->nej
