---
title: "Övningar: Villkor"
format:
  html:
    fontsize: 1em
    css: style.css
    title-block: false
execute: 
  echo: false
---

### Övning 1

För de booleska variablerna `a`, `b` och `c` gäller

* `a = True`
* `b = True`
* `c = False`

Fundera ut vilket booleskt värde respektive uttryck nedan kommer att anta,
och kontrollera det därefter i Pythonskalet i Thonny.

a. `(a and b) and c`
b. `a and b and c`
c. `(a and c) or b`
d. `a and b or c`

### Övning 2 {#villkor-smycke}

Skapa ett program i [EduBlocks](https://app.edublocks.org/) eller i en
Pythonmiljö som ber dig mata ingett belopp med pengar. Programmet ska avgöra om
det räcker till att köpa ett smycke av järn, silver eller guld. Skapa även ett
flödesschema för programmet.

Priset för respektive typ av smycke deklareras som variabler, där ett järnmycke
kostar 200 kr, ett silversmycke 500 kr och ett guldsmycke 1000 kr. Deklarera
variabler för dessa priser och använd dessa i programmet.

:::{.callout-note appearance="minimal"}

```         
# Exempelkörning 1
Ange belopp (i kr.) att handla för -> 300
Beloppet räcker till ett järnsmycke!

# Exempelkörning 2
Ange belopp (i kr.) att handla för -> 800
Beloppet räcker till ett ett silversmycke!

# Exempelkörning 3
Ange belopp (i kr.) att handla för -> 100
Beloppet räcker inte till något smycke.
```
:::

:::{.callout-tip collapse="true" icon="false" title="Lösningsförslag övning 2"}

[Se flödesschema här](https://gist.github.com/codebubo/5909fb477c99db600505702292b277cf)

**Lösningsförslag för typavgörandet** (första delövningen)

```python
# Detta program demonstrerar hur en if-sats
# kan vare uppbyggd med elif och else.
pris_järn = 200
pris_silver = 500
pris_guld = 1000

belopp = int(input("Ange belopp (i kr.) att handla för -> "))

if belopp >= pris_guld:
  print("Beloppet räcker till ett guldsmycke!")
    
elif belopp >= pris_silver: # Om inte tidigare villkor är uppfyllt så prövas detta villkor
  print("Beloppet räcker till ett silversmycke!")

elif belopp >= pris_järn:   # Om inte tidigare villkor är uppfyllt så prövas detta villkor
  print("Beloppet räcker till ett järnsmycke!")

else:                       # Om inget av villkoren är uppfyllda så körs nedanstående sats
  print("Beloppet räcker inte till något smycke.")

print("Programmet avslutas")# Denna sats ligger utanför villkorssatsen
```
:::

### Övning 3 {#villkor-trianglar}

Skapa ett program i [EduBlocks](https://app.edublocks.org/) eller i en
Pythonmiljö som läser in längderna på tre sidor. Programmet ska sedan avgöra om
dessa sidor kan ingå i en rätvinklig triangel.

:::{.callout-note appearance="minimal"}

``` 
# Exempelkörning 1
Ange längden på sida 1 -> 3
Ange längden på sida 2 -> 4
Ange längden på sida 3 -> 5
Sidorna 3, 4 och 5 kan bilda en rätvinklig triangel

# Exempelkörning 2
Ange längden på sida 1 -> 3
Ange längden på sida 2 -> 4
Ange längden på sida 3 -> 6
Sidorna 3, 4 och 6 kan inte bilda inte en rätvinklig triangel
```
:::

:::{.callout-note title="Tips"}
Använd Pythagoras sats för avgörandet. För att kvadrera ett tal används
*exponentoperatorn* `**`. T ex gäller att `a = 3**2` motsvarar $a=3^2$, vilket
är `9`.
:::

:::{.callout-tip collapse="true" icon="false" title="Lösningsförslag övning 3"}

```python
# Detta program avgör om tre sidor med given längd kan bilda en rätvinklig
# triangel.
# Framförallt demonstrerar programmet användadet av de booleska satserna
# "and" och "or", jämförande likheter och exponmenter.

a = int(input("Ange sida a -> "))
b = int(input("Ange sida b -> "))
c = int(input("Ange sida c -> "))

# Kontrollerar om Pythagoras sats gäller för någon kombination av sidorna
if (a**2 + b**2 == c**2) or (a**2 + c**2 == b**2) or (b**2 + c**2 == a**2):
    print(f"Sidorna {a}, {b} och {c} kan bilda en rätvinklig triangel")
else:
    print(f"Sidorna {a}, {b} och {c} kan inte bilda en rätvinklig triangel")

print("Programmet avslutas")
```
:::

### Övning 4 {#villkor-provpoang}

Ett program som skriver ut vilket betyg en viss provpoäng motsvarar skulle
kunna se ut så här:

```python
e_gräns = 15; c_gräns = 25; a_gräns = 35
poäng = int(input('Ange din provpoäng -> '))
if poäng >= a_gräns:
   print('A')
elif poäng >= c_gräns:
   print('C')
elif poäng >= e_gräns:
   print('E')
else:
   print('F')
print('Programmet avslutas')
```

a. Gör ett flödesschema för programmet.
b. Skriv om programmet så att det använder de booleska operatorerna
`not`, `and` och `or` i villkoren.

:::{.callout-tip collapse="true" icon="false" title="Lösningsförslag övning 4"}

[Se flödesschema här](https://gist.github.com/codebubo/be43369abc47aa71312423d561d4de8c)

**Omskrivning av givet program med booleska operatorer**

```python
# Program som skriver ut ett erhållet betyg baserat på
# givna gränser. Programmet demonstrerar användandet av
# de booleska operatorerna and och not.

e_gräns = 15
c_gräns = 25
a_gräns = 35

poäng = int(input('Ange din provpoäng -> '))

if poäng >= e_gräns and not poäng >= c_gräns:
    print("E")
elif poäng >= c_gräns and not poäng >= a_gräns:
    print("C")
elif poäng >= a_gräns:
    print("A")
else:
    print("F")
```

:::

### Övning 5 {#villkor-skottar}

Skapa ett program som ber dig mata in ett årtal.
Programmet avgör om året är ett skottår.
Ett årtal som inte är delbart med 4 är inte ett skottår. Är
årtalet dessutom delbart 100 måste det också vara delbart med
400 för att vara ett skottår.


:::{.callout-note appearance="minimal"}

```      
# Exempelkörning 1
Ange ett årtal ->  2020
År 2020 är ett skottår

# Exempelkörning 2
Ange ett årtal ->  2021
År 2021 är inte ett skottår

# Exempelkörning 3
Ange ett årtal ->  1800
År 1800 är inte ett skottår

# Exempelkörning 4
Ange ett årtal ->  2000
År 2000 är ett skottår
```
:::

:::{.callout-note title="Tips"}

Modulooperatorn (`%`) ger resultatet **noll** om ett tal är jämnt
delbart med ett annat.

```
# Exempel 1, delbart
# (21 är delbart med 3)
21 % 3
0
```

```
# Exempel 2, ej delbart
# (21 är ej delbart med 2)
21 % 2
1
```
:::

:::{.callout-tip collapse="true" icon="false" title="Lösningsförslag övning 5"}

**Variant 1**, med sammansättande and-sats och villkor
som skrivs ut i sin helhet:
```python
# Program som avgör om ett år är skottår.
# Programmet demonstrerar villkor där modulooperatorn
# används. Här används egenskapen att om tal a är jämnt
# delbart med tal b så gäller att a % b är noll.
# Denna version använder en sammansättande boolesk
# operator (and) istället för nästlad if-sats.

årtal = int(input("Ange ett årtal -> "))
if årtal % 400 == 0:                         # Årtal jämnt delbart med 400
    print(f"År {årtal} är ett skottår")
elif årtal % 4 == 0 and årtal % 100 == 0:    # Årtal jämnt delbart med 4 och 100 men inte med 400
    print(f"År {årtal} är inte ett skottår")
elif årtal % 4 == 0:                         # Årtal jämnt delbart med 4, men inte med 100
    print(f"År {årtal} är ett skottår")
else:                                        # Årtal inte jämnt delbart med 4
    print(f"År {årtal} är inte ett skottår")
```

**Variant 2**, samma uppbyggnad som Variant 1. Istället
för att jämföra resultatet resultatet av modulo med noll
med hjälp av jämförelseoperatorn `==` så används den booleska
operatorn `not`. 

```python
# Program som avgör om ett år är skottår.
# Programmet demonstrerar villkor där modulooperatorn
# används. Här används egenskapen att om tal a är jämnt
# delbart med tal b så gäller att a % b är noll (eller False).
# Denna version använder en sammansättande boolesk
# operator istället för nästlad if-sats. Istället för
# skriva ut nolljämförelsen så används `not`-operatorn.

årtal = int(input("Ange ett årtal -> "))
if not årtal % 400:                      # Årtal jämnt delbart med 400
    print(f"År {årtal} är ett skottår")
elif not årtal % 4 and not årtal % 100:  # Årtal jämnt delbart med 4 och 100 men inte med 400
    print(f"År {årtal} är inte ett skottår")
elif not årtal % 4:                      # Årtal jämnt delbart med 4, men inte med 100
    print(f"År {årtal} är ett skottår")
else:                                    # Årtal inte jämnt delbart med 4
    print(f"År {årtal} är inte ett skottår")
```

**Variant 3**, uppbyggnad av programmet med nästlade `if`-satser istället för
booleska operatorer och jämförelseoperatorer.

```python
# Program som avgör om ett år är skottår.
# Programmet demonstrerar villkor där modulooperatorn
# används. Här används egenskapen att om tal a är jämnt
# delbart med tal b så gäller att a % b är noll (eller False).
# Istället för booleska operatorer så använder programmet
# nästlade if-sats.

årtal = int(input("Ange ett årtal -> "))

if årtal % 4:           # Årtal är inte jämnt delbart med 4
    print(f"År {årtal} är inte ett skottår")
else:                   # Årtal är jämnt delbart med 4
    if årtal % 100:     # Årtal jämnt delbart med 4, men inte med 100
        print(f"År {årtal} är ett skottår")
    else:               # Årtal jämnt delbart med 4 och med 100
        if årtal % 400: # Årtal jämnt delbart med 4 och 100, men inte med 400
            print(f"År {årtal} är inte ett skottår")
        else:           # Årtal jämnt delbart med 4, 100 och 400
            print(f"År {årtal} är ett skottår")
```

:::

## Några mer utmanande övningar

### Övning 6

Justera programmet i [Övning 3](#villkor-trianglar) så att programmet avgör om
de tre sidorna kan bilda en triangel över huvud taget.

:::{.callout-note appearance="minimal"}

```         
# Exempelkörning
Ange längden på sida 1 -> 7
Ange längden på sida 2 -> 5
Ange längden på sida 3 -> 1
Dessa sidor kan inte bilda en triangel
```
:::


### Övning 7

Detta problem bygger på [Övning 2](#villkor-smycke).
Förbättra  programmet så att det skriver ut det maximala antalet smycken av
respektive sort smycke som du kan köpa för ett angivet belopp.
Programmet ska prioritera de dyraste smyckena.

:::{.callout-note appearance="minimal"}

```         
# Exempelkörning
Ange belopp (i kr.) att handla för -> 2950
Beloppet räcker till:
Antal guldsmycken:  2
Antal silvermycken: 1
Antal järnsmycken:  2
Belopp kvar: 50 kr
```

Siffrorna som anger antalet ska vara högerjusterade!

```{python}
#| echo: false
# Detta program beräknar hur många smycken av järn,
# silver respektive guld med ett givet pris som kan
# köpas för ett givet belopp. Programmet demonstrerar
# heltalsdivision och ändring av variabelvärde, men
# även hur ett heltal kan matas in och användning av
# f-string.

pris_järn = 200
pris_silver = 500
pris_guld = 1000

# belopp = int(input("Ange belopp att handla för -> "))
belopp = 2950
belopp_kvar = belopp

# Hantering av guldsmycken
antal_guld = belopp_kvar // pris_guld     # Variabeln antal_guld skapas och tilldelas ett värde
belopp_kvar -= antal_guld * pris_guld     # Här ändras variabelvärdet belopp_kvar

# Hantering av silversmycken
antal_silver = belopp_kvar // pris_silver # Variabeln antal_silver skapas och tilldelas ett värde
belopp_kvar -= antal_silver * pris_silver # Här ändras variabelvärdet belopp_kvar

# Hantering av järnsmycken
antal_järn = belopp_kvar // pris_järn     # Variabeln antal_järn skapas och tilldelas ett värde
belopp_kvar -= antal_järn * pris_järn     # Här ändras variabelvärdet belopp_kvar

#print("Beloppet räcker till:")
#print(f"Antal guldsmycken: {antal_guld}")
#print(f"Antal silversmycken: {antal_silver}")
#print(f"Antal järnsmycken: {antal_järn}")

#print(f"Belopp kvar: {belopp_kvar} kr")

#print("Programmet avslutas")
```

:::

:::{.callout-note title="Tips"}

Använd heltalsdivision, den ger **heltalsdelen**
vid division. Exempel:

```
15 // 7 # Ger resultatet 2
20 // 7 # Ger resultatet 2
```
:::
